/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.ifpr.crudta.main;

import org.ifpr.crudta.produto.Produto;
import org.ifpr.crudta.produto.dao.ProdutoDAO;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author IFPR
 */
public class ProdutoFormJDialog extends javax.swing.JDialog {

    private DateTimeFormatter dateTimeFormatter;
    private ProdutoDAO produtoDAO;
    private Produto produto;
    private Border bordaOriginal;
    private Border bordaErro;

    /**
     * Creates new form ProdutoFormJDialog
     */
    public ProdutoFormJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        produtoDAO = new ProdutoDAO();
        bordaOriginal = nomeTF.getBorder();
        bordaErro = BorderFactory.createLineBorder(Color.RED);
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    public void objectToForm() {
        nomeTF.setText(produto.getNome());
        marcaTF.setText(produto.getMarca());
        dataFabricacaoTF.setText(produto.getDataFabricacao().format(dateTimeFormatter));
        precoTF.setText(produto.getPreco().toString());
    }

    public void formToObject() {
        produto.setNome(nomeTF.getText());
        produto.setMarca(marcaTF.getText());
        produto.setDataFabricacao(LocalDate.parse(dataFabricacaoTF.getText(), dateTimeFormatter));
        produto.setPreco(new BigDecimal(precoTF.getText()));
    }

    private boolean isFormValid() {
        boolean isValid = true;

        if (nomeTF.getText().strip().isBlank()) {
            nomeTF.setBorder(bordaErro);
            isValid = false;
        } else {
            nomeTF.setBorder(bordaOriginal);
        }

        if (marcaTF.getText().strip().isBlank()) {
            marcaTF.setBorder(bordaErro);
            isValid = false;
        } else {
            marcaTF.setBorder(bordaOriginal);
        }

        if (dataFabricacaoTF.getText().strip().isBlank() || dataFabricacaoTF.getText().strip().length() != 10) {
            dataFabricacaoTF.setBorder(bordaErro);
            isValid = false;
        } else {
            dataFabricacaoTF.setBorder(bordaOriginal);
        }

        if (precoTF.getText().strip().isBlank()) {
            precoTF.setBorder(bordaErro);
            isValid = false;
        } else {
            precoTF.setBorder(bordaOriginal);
        }

        try {
            new BigDecimal(precoTF.getText());
            precoTF.setBorder(bordaOriginal);
        } catch (NumberFormatException e) {
            precoTF.setBorder(bordaErro);
            isValid = false;
        }


        return isValid;
    }

    public void limparCampos() {
        nomeTF.setText("");
        nomeTF.setBorder(bordaOriginal);
        marcaTF.setText("");
        marcaTF.setBorder(bordaOriginal);
        dataFabricacaoTF.setText("");
        dataFabricacaoTF.setValue(null);
        dataFabricacaoTF.setBorder(bordaOriginal);
        precoTF.setText("");
        precoTF.setValue(null);
        precoTF.setBorder(bordaOriginal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        tituloLB = new javax.swing.JLabel();
        nomeLB = new javax.swing.JLabel();
        marcaLB = new javax.swing.JLabel();
        dataFabricacaoLB = new javax.swing.JLabel();
        precoLB = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        marcaTF = new javax.swing.JTextField();
        dataFabricacaoTF = new javax.swing.JFormattedTextField();
        precoTF = new javax.swing.JFormattedTextField();
        camposObrigatoriosLB = new javax.swing.JLabel();
        salvarBT = new javax.swing.JButton();
        cancelarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLB.setText("Dados do Produto");

        nomeLB.setText("Nome:*");

        marcaLB.setText("Marca:*");

        dataFabricacaoLB.setText("Data de Fabricação:*");

        precoLB.setText("Preço:*");

        try {
            dataFabricacaoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        precoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        camposObrigatoriosLB.setText("* Campos obrigatórios");

        salvarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        cancelarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-circle.png"))); // NOI18N
        cancelarBT.setText("Cancelar");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataFabricacaoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marcaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTF)
                            .addComponent(marcaTF)
                            .addComponent(dataFabricacaoTF)
                            .addComponent(precoTF)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(camposObrigatoriosLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(cancelarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvarBT)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLB)
                .addGap(34, 34, 34)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLB)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLB)
                    .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataFabricacaoLB)
                    .addComponent(dataFabricacaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precoLB)
                    .addComponent(precoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camposObrigatoriosLB)
                    .addComponent(salvarBT)
                    .addComponent(cancelarBT))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        this.dispose();
        limparCampos();
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        if (!isFormValid()) {
            JOptionPane.showMessageDialog(this, "Formulário inválido, por favor verifique os campos em vermelho", "ERRO DE VERIFICAÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        formToObject();

        if (produto.getId() == 0) {
            produtoDAO.create(produto);
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            produtoDAO.update(produto);
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
        }

        this.dispose();
    }//GEN-LAST:event_salvarBTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camposObrigatoriosLB;
    private javax.swing.JButton cancelarBT;
    private javax.swing.JLabel dataFabricacaoLB;
    private javax.swing.JFormattedTextField dataFabricacaoTF;
    private javax.swing.JLabel marcaLB;
    private javax.swing.JTextField marcaTF;
    private javax.swing.JLabel nomeLB;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JLabel precoLB;
    private javax.swing.JFormattedTextField precoTF;
    private javax.swing.JButton salvarBT;
    private javax.swing.JLabel tituloLB;
    // End of variables declaration//GEN-END:variables
}
